version: '3.8'

services:
  main_app:
    build: 
      context: ./server
    container_name: main_app
    restart: always
    ports:
      - "8000:8000"
    # НЕ перезаписываем весь /app, иначе бинарник и .env сольются!
    # Вместо этого монтируем только подкаталог для данных (db file):
    volumes:
      - db_data:/app/data
    networks:
      - backend

  agent:
    build:
      context: ./agent
    container_name: agent
    restart: always
    networks:
      - backend
  
  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - backend
    depends_on:
      - main_app


volumes:
  db_data:

networks:
  backend:
