version: '3.8'

services:
  #frontend:
    # build:
    #   context: ./client
    # container_name: frontend
    # restart: always
    # ports:
    #   - "3000:80"
    # networks:
    #   - backend

  main_app:
    build:
      context: ./server
    container_name: main_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data
    networks:
      - backend

  agent:
    build:
      context: ./agent
    container_name: agent
    restart: always
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
