FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o main .

# --- Final Stage ---
FROM alpine:latest

WORKDIR /app

RUN apk update && apk add --no-cache ca-certificates

COPY --from=builder /app/main .
COPY --from=builder /app/.env .

EXPOSE 50051

CMD ["./main"]